version: '3.3'
services:
  mysql-db:
    image: mysql:8.0
    container_name: musa-mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'approval_system'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
  telegram-chatbot:
    image: telegram-chatbot:0.1
    container_name: telegram-chatbot
    restart: always
    environment:
      DB_HOST: musa-mysql
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '7050:7050'
    expose:
      - '7050'
    depends_on:
      - mysql-db   
# Names our volume
volumes:
  my-db: {}
